-- MySQL Script generated by MySQL Workbench
-- Tue Mar 14 12:05:52 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema store
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema store
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `store` DEFAULT CHARACTER SET utf8 ;
USE `store` ;

-- -----------------------------------------------------
-- Table `store`.`personas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`personas` (
  `id_persona` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(30) NOT NULL,
  `lastname` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id_persona`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`recomendaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`recomendaciones` (
  `id_recomendacion` INT NOT NULL AUTO_INCREMENT,
  `nombre_recomendacion` VARCHAR(30) NOT NULL,
  `comentario_recomendacion` VARCHAR(200) NOT NULL,
  `fecha_recomendacion` DATE NOT NULL,
  `img_recomendacion` VARCHAR(200) NOT NULL,
  PRIMARY KEY (`id_recomendacion`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`recomendaciones`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`contactos` (
  `id_contact` INT NOT NULL AUTO_INCREMENT,
  `nombre_contact` VARCHAR(30) NOT NULL,
  `apellido_contact` VARCHAR(30) NOT NULL,
  `asunto_contact` VARCHAR(50) NOT NULL,
  `mail_contact` VARCHAR(30) NOT NULL,
  `mensaje_contact` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_contact`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`users` (
  `id_user` INT NOT NULL AUTO_INCREMENT,
  `mail` VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  `id_persona` INT NOT NULL,
  PRIMARY KEY (`id_user`, `id_persona`),
  UNIQUE INDEX `mail_UNIQUE` (`mail` ASC),
  INDEX `fk_users_personas1_idx` (`id_persona` ASC),
  CONSTRAINT `fk_users_personas1`
    FOREIGN KEY (`id_persona`)
    REFERENCES `store`.`personas` (`id_persona`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`categorias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`categorias` (
  `id_categoria` INT NOT NULL AUTO_INCREMENT,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`),
  UNIQUE INDEX `nombreCategoria_UNIQUE` (`nombre_categoria` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`items` (
  `id_item` INT NOT NULL AUTO_INCREMENT,
  `nombre_item` VARCHAR(45) NOT NULL,
  `precio_item` INT NOT NULL,
  `stock_item` INT NOT NULL,
  `estado_item` VARCHAR(30) NOT NULL,
  `img1` VARCHAR(120) NOT NULL,  
  `img2` VARCHAR(120) NOT NULL,
  `img3` VARCHAR(120) NOT NULL,
  `id_categoria` INT NOT NULL,
  PRIMARY KEY (`id_item`, `id_categoria`),
  INDEX `fk_items_categorias1_idx` (`id_categoria` ASC),
  CONSTRAINT `fk_items_categorias1`
    FOREIGN KEY (`id_categoria`)
    REFERENCES `store`.`categorias` (`id_categoria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `store`.`compras`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `store`.`compras` (
  `id_compra` INT NOT NULL AUTO_INCREMENT,
  `comentario` VARCHAR(255) NOT NULL,
  `fecha` DATE NOT NULL,
  `estado_pedido` VARCHAR(45) NOT NULL,
  `id_item` INT NOT NULL,
  `id_user` INT NOT NULL,
  PRIMARY KEY (`id_compra`, `id_item`, `id_user`),
  INDEX `fk_compras_items1_idx` (`id_item` ASC),
  INDEX `fk_compras_users1_idx` (`id_user` ASC),
  CONSTRAINT `fk_compras_items1`
    FOREIGN KEY (`id_item`)
    REFERENCES `store`.`items` (`id_item`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_compras_users1`
    FOREIGN KEY (`id_user`)
    REFERENCES `store`.`users` (`id_user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
